// Code generated by MockGen. DO NOT EDIT.
// Source: ./tss/coordinator.go

// Package mock_tss is a generated GoMock package.
package mock_tss

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	peer "github.com/libp2p/go-libp2p-core/peer"
)

// MockTssProcess is a mock of TssProcess interface.
type MockTssProcess struct {
	ctrl     *gomock.Controller
	recorder *MockTssProcessMockRecorder
}

// MockTssProcessMockRecorder is the mock recorder for MockTssProcess.
type MockTssProcessMockRecorder struct {
	mock *MockTssProcess
}

// NewMockTssProcess creates a new mock instance.
func NewMockTssProcess(ctrl *gomock.Controller) *MockTssProcess {
	mock := &MockTssProcess{ctrl: ctrl}
	mock.recorder = &MockTssProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTssProcess) EXPECT() *MockTssProcessMockRecorder {
	return m.recorder
}

// Ready mocks base method.
func (m *MockTssProcess) Ready(readyMap map[peer.ID]bool, excludedPeers []peer.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready", readyMap, excludedPeers)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ready indicates an expected call of Ready.
func (mr *MockTssProcessMockRecorder) Ready(readyMap, excludedPeers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockTssProcess)(nil).Ready), readyMap, excludedPeers)
}

// SessionID mocks base method.
func (m *MockTssProcess) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockTssProcessMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockTssProcess)(nil).SessionID))
}

// Start mocks base method.
func (m *MockTssProcess) Start(ctx context.Context, coordinator bool, resultChn chan interface{}, errChn chan error, params []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, coordinator, resultChn, errChn, params)
}

// Start indicates an expected call of Start.
func (mr *MockTssProcessMockRecorder) Start(ctx, coordinator, resultChn, errChn, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTssProcess)(nil).Start), ctx, coordinator, resultChn, errChn, params)
}

// StartParams mocks base method.
func (m *MockTssProcess) StartParams(readyMap map[peer.ID]bool) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartParams", readyMap)
	ret0, _ := ret[0].([]string)
	return ret0
}

// StartParams indicates an expected call of StartParams.
func (mr *MockTssProcessMockRecorder) StartParams(readyMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartParams", reflect.TypeOf((*MockTssProcess)(nil).StartParams), readyMap)
}

// Stop mocks base method.
func (m *MockTssProcess) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTssProcessMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTssProcess)(nil).Stop))
}
