// Code generated by MockGen. DO NOT EDIT.
// Source: ./chains/btc/executor/message-handler.go

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	big "math/big"
	reflect "reflect"

	store "github.com/ChainSafe/sygma-relayer/store"
	btcjson "github.com/btcsuite/btcd/btcjson"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	gomock "github.com/golang/mock/gomock"
	message "github.com/sygmaprotocol/sygma-core/relayer/message"
)

// MockBlockFetcher is a mock of BlockFetcher interface.
type MockBlockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockBlockFetcherMockRecorder
}

// MockBlockFetcherMockRecorder is the mock recorder for MockBlockFetcher.
type MockBlockFetcherMockRecorder struct {
	mock *MockBlockFetcher
}

// NewMockBlockFetcher creates a new mock instance.
func NewMockBlockFetcher(ctrl *gomock.Controller) *MockBlockFetcher {
	mock := &MockBlockFetcher{ctrl: ctrl}
	mock.recorder = &MockBlockFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockFetcher) EXPECT() *MockBlockFetcherMockRecorder {
	return m.recorder
}

// GetBestBlockHash mocks base method.
func (m *MockBlockFetcher) GetBestBlockHash() (*chainhash.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBestBlockHash")
	ret0, _ := ret[0].(*chainhash.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBestBlockHash indicates an expected call of GetBestBlockHash.
func (mr *MockBlockFetcherMockRecorder) GetBestBlockHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBestBlockHash", reflect.TypeOf((*MockBlockFetcher)(nil).GetBestBlockHash))
}

// GetBlockVerboseTx mocks base method.
func (m *MockBlockFetcher) GetBlockVerboseTx(arg0 *chainhash.Hash) (*btcjson.GetBlockVerboseTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockVerboseTx", arg0)
	ret0, _ := ret[0].(*btcjson.GetBlockVerboseTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockVerboseTx indicates an expected call of GetBlockVerboseTx.
func (mr *MockBlockFetcherMockRecorder) GetBlockVerboseTx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockVerboseTx", reflect.TypeOf((*MockBlockFetcher)(nil).GetBlockVerboseTx), arg0)
}

// MockPropStorer is a mock of PropStorer interface.
type MockPropStorer struct {
	ctrl     *gomock.Controller
	recorder *MockPropStorerMockRecorder
}

// MockPropStorerMockRecorder is the mock recorder for MockPropStorer.
type MockPropStorerMockRecorder struct {
	mock *MockPropStorer
}

// NewMockPropStorer creates a new mock instance.
func NewMockPropStorer(ctrl *gomock.Controller) *MockPropStorer {
	mock := &MockPropStorer{ctrl: ctrl}
	mock.recorder = &MockPropStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropStorer) EXPECT() *MockPropStorerMockRecorder {
	return m.recorder
}

// PropStatus mocks base method.
func (m *MockPropStorer) PropStatus(source, destination uint8, depositNonce uint64) (store.PropStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PropStatus", source, destination, depositNonce)
	ret0, _ := ret[0].(store.PropStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PropStatus indicates an expected call of PropStatus.
func (mr *MockPropStorerMockRecorder) PropStatus(source, destination, depositNonce interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PropStatus", reflect.TypeOf((*MockPropStorer)(nil).PropStatus), source, destination, depositNonce)
}

// StorePropStatus mocks base method.
func (m *MockPropStorer) StorePropStatus(source, destination uint8, depositNonce uint64, status store.PropStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePropStatus", source, destination, depositNonce, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePropStatus indicates an expected call of StorePropStatus.
func (mr *MockPropStorerMockRecorder) StorePropStatus(source, destination, depositNonce, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePropStatus", reflect.TypeOf((*MockPropStorer)(nil).StorePropStatus), source, destination, depositNonce, status)
}

// MockDepositProcessor is a mock of DepositProcessor interface.
type MockDepositProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockDepositProcessorMockRecorder
}

// MockDepositProcessorMockRecorder is the mock recorder for MockDepositProcessor.
type MockDepositProcessorMockRecorder struct {
	mock *MockDepositProcessor
}

// NewMockDepositProcessor creates a new mock instance.
func NewMockDepositProcessor(ctrl *gomock.Controller) *MockDepositProcessor {
	mock := &MockDepositProcessor{ctrl: ctrl}
	mock.recorder = &MockDepositProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositProcessor) EXPECT() *MockDepositProcessorMockRecorder {
	return m.recorder
}

// ProcessDeposits mocks base method.
func (m *MockDepositProcessor) ProcessDeposits(blockNumber *big.Int) (map[uint8][]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDeposits", blockNumber)
	ret0, _ := ret[0].(map[uint8][]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDeposits indicates an expected call of ProcessDeposits.
func (mr *MockDepositProcessorMockRecorder) ProcessDeposits(blockNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDeposits", reflect.TypeOf((*MockDepositProcessor)(nil).ProcessDeposits), blockNumber)
}
