# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: BUSL-1.1

on: [pull_request]
name: Linter check
env:
  GO111MODULE: on

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: actions/checkout@v2

      - name: Install linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Run linter
        run: golangci-lint run --timeout=10m

  vet-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18.x"
      - uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...
