# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

name: Sygma Devnet

on:
  push:
    branches:
      - main

run-name: Deploy Relayers to Devnet - ${{ inputs.release_tag }} by @${{ github.actor }}

env:
  REGISTRY: 'sprinterux'
  TAG: 'dev'
  DOCKER_CONTENT_TRUST: '1'

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build / tag / push docker image into Docker Hub
        id: build-and-push-tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ env.TAG }},${{ env.REGISTRY }}/${{ github.event.repository.name }}:${{ env.TAG }}-${{ github.ref_name }}
